#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
name: Build a Pelican Website
on:
  push:
    # This prevents the workflow from running automatically on a new branch
    # When creating a new site branch, please ensure that the push and checkout branches agree
    # and that the action/pelican destination value is updated accordingly
    branches: [ "SOURCE_BRANCH" ]
  workflow_dispatch:
jobs:
  build-pelican:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # This must equal the push/branches list above, and be appropriate for the destination below
          ref: 'SOURCE_BRANCH'
      - uses: apache/infrastructure-actions/pelican@main
        with:
          # This must be appropriate for the branch being built
          destination: 'DESTINATION_BRANCH'
          gfm: 'true'
