name: Build a Pelican Website
description: "Generate a Pelican website from Markdown"    
inputs:
  destination:
    description: "Pelican Output branch"
    required: true
    default: "asf-site"
  gfm:
    description: "Uses GitHub Flavored Markdown"
    required: false
    default: 'false'
  output:
    description: "Pelican generated output directory"
    required: false
    default: 'output'
  tempdir:
    description: "Temporary Directory name"
    required: false
    default: '../output.tmp'
  debug:
    description: "Pelican Debug mode"
    required: false
    default: 'false'
  version:
    description: "Pelican Version (default 4.5.4)"
    required: false
    default: '4.5.4'
runs:
  using: "composite"
  steps:
    - name: Install Pelican
      # Install needs to run in separate shell so stdout is restored
      run: |
        (
          test "${{ inputs.debug }}" == 'true' || exec >/dev/null
          pip3 install pelican==${{ inputs.version }} markdown ghp-import bs4 ezt requests
        )
        python3 -V
        echo "Pelican version:"
        pelican --version
        if [ "${{ inputs.debug }}" == 'true' ]
        then
          pip3 list # This a long list
        fi
      shell: bash

    # If the site uses Github Flavored Markdown, use this build branch
    - name: fetch and build libcmark-gfm.so
      run: |
        {
          # Don't pollute site checkout
          cd ..
          cmake --version
          # disable stdout unless debug is on
          if [ "${{ inputs.debug }}" == 'true' ]
          then
            DEBUG_STEPS=1; export DEBUG_STEPS
          else
            exec >/dev/null
          fi
          bash ${{ github.action_path }}/build-cmark.sh
        }
      shell: bash
      if: ${{ inputs.gfm == 'true' }}

    - name: Generate website from markdown
      run: |
        if [ "${{ inputs.debug }}" == 'true' ]
        then
          OPTS='-D'
        else
          OPTS=''
        fi
        echo "Getting plugins from action location: ${{ github.action_path }}"
        PP=$(python3 ${{ github.action_path }}/plugin_paths.py '${{ github.action_path }}/plugins')
        /usr/bin/env python3 -B -m pelican content -e "$PP" -o ${{ inputs.tempdir }} $OPTS
      shell: bash
      env: # in case we are using GFM (otherwise ignored)
        LIBCMARKDIR: "../cmark-gfm-0.28.3.gfm.12/lib"

    - name: Check out previous branch
      shell: bash
      continue-on-error: true
      run: | 
        git config --global user.email "private@infra.apache.org"
        git config --global user.name "Build Pelican (action)"
        git remote update
        if git checkout ${{ inputs.destination }}
        then
          git pull origin ${{ inputs.destination }}
        else
          # if none, create it.
          echo "branch ${{ inputs.destination }} is new; create empty site"
          git switch --orphan ${{ inputs.destination }}
          git checkout origin/${{ github.ref_name }} -- .asf.yaml
          git add .asf.yaml -f
          git commit -m "Initialise empty site"
          git push -u origin ${{ inputs.destination }}
        fi

    - name: Commit Directly to the branch
      shell: bash
      run: |
        # Remove all existing output so deletions will be captured
        rm -rf ${{ inputs.output }}
        git rm --quiet -r --ignore-unmatch --cached ${{ inputs.output }}/*
        # replace with generated output
        mv ${{ inputs.tempdir }} ${{ inputs.output }}
        git diff # Show changes
        git add ${{ inputs.output }}
        git status
        if git commit -m "Commit build products"
          then
              git push
        else
          echo "No change"
          true # ensure step is successful
        fi
